package com.fatima.UAHogar.modelo;

public enum TipoNotificacion {UNION_HOGAR,
    INCIDENCIA_NUEVA,
    INCIDENCIA_CERRADA,
    TAREA_ASIGNADA,
    TAREA_URGENTE,
    TAREA_MARGEN_GRACIA,
    TAREA_COMPLETADA,
    TAREA_VENCIDA,
    MENSAJE_NUEVO,
    EXPULSADO_HOGAR,
    INTERCAMBIO_SOLICITADO,
    INTERCAMBIO_ACEPTADO,
    INTERCAMBIO_RECHAZADO,
    INTERCAMBIO_CADUCADO
}